Add containsOnce matcher
dart-lang/matcher pull request #198
Opened 2022-11-15 21:17 UTC by icmdaf

Matches [Iterable]s where exactly one element matches the expected value, and all other elements don't match.

2022-11-16 01:27 UTC, natebosch requested changes

2022-11-16 01:27 UTC, natebosch commented on lib/src/iterable_matchers.dart
> +    }
```suggestion
    var matches = [
      for (var value in item)
        if (matcher.matches(value, matchState)) value,
    ];
```

2022-11-16 01:27 UTC, natebosch commented
@jakemac53 - any concerns with this matcher?

2022-11-16 15:39 UTC, jakemac53 commented
No particular concerns on my part

2022-11-17 01:03 UTC, natebosch approved these changes

2022-11-17 01:04 UTC, merged